### ISSUE TITLE
Check your snapraid vars

### ISSUE THREAD

**Issue by mnightingale** [ironicbadger/infra#12]
After copying part of your snapraid config I noticed emails were not configured correctly, it seems variables were renamed a while ago in [ironicbadger/ansible-role-snapraid](https://github.com/ironicbadger/ansible-role-snapraid) but morpheus seems to still use the old variable names.

Thought you might want to check.

https://github.com/ironicbadger/infra/blob/781dad5500d02268a5050b71f8fa7afee8e798d5/group_vars/morpheus.yaml#L234-L236

**Comment by ironicbadger** [comment]
Thank you! Fixed with this [commit](https://github.com/ironicbadger/infra/commit/ac78c08843dbad21160cc2ff48abbb03a8555ee9).
