### ISSUE TITLE
Re-organize nix home-manager modules

### ISSUE THREAD

**Issue by mjmaurer** [ironicbadger/infra#17]
Re-organize nix home manager modules. Should have 3 directories for different types: - 'configuration': for config files where the actual installation of the program is handled elswhere - 'programs': for programs that are installed and configured via nix - 'services': for services that are installed and configured via nix

See obsidian.nix for an example

**Comment by ironicbadger** [comment]
could you link out to obsidian.nix?

**Comment by mjmaurer** [comment]
Ah I'm so sorry, I have an editor plugin for creating issues and it looks like it submits to the original repo (when I meant to add this to my fork)
