### ISSUE TITLE
Question: How main user is linked to docker group ?

### ISSUE THREAD

**Issue by oncleben31** [IronicBadger/infra#6]
Hello, 

Your repository is a good source to learn ANSIBLE and to understand how the PMS is constructed.

I don't see how you link your main user with docker group in the `cartman` server.
From my understanding this is required to be able to manage docker without sudo.

And from my browsing in this repo, the role to update your user is commented: `ironicbadger.ansible_users`

Can you clarify this par

**Comment by IronicBadger** [comment]
Looks like I cheated and ran `usermod -aG docker alex` a while ago and hadn't noticed this oversight. Thanks for pointing it out.
