### ISSUE TITLE
dfzfs - should this have a -t zfs?

### ISSUE THREAD

**Issue by liambresnahan** [IronicBadger/infra#8]
Firstly - thanks - I've been using your repo to helpfully learn ansible and a number of concepts around your perfect media server - I now have something setup that is working very well. 

I noticed that running `dfzfs` as defined in the bash aliases that I wasn't seeing any zfs volumes. I didn't know if you expected that but based on the name I assume not. Should I submit a PR to correct? looks like that's the big difference between dfclean and dfzfs so I assume it should include a -t zfs on the dfzfs alias, right?

Thanks again!

**Comment by IronicBadger** [comment]
You're probably right. PRs welcome.
